out_dir: "results/"
use_cache: True # can also use --no-cache in the CLI

data:
  lidar_frequency: 10.0 # only valid if deskew==True
  preprocess: True
  max_range: 100.0 # can be also changed in the CLI
  min_range: 5.0

mapping:
  # voxel_size: 1.0 # <- optional
  max_points_per_voxel: 20

adaptive_threshold:
  initial_threshold: 2.0
  min_motion_th: 0.1
