out_dir: "results"

data:
  deskew: False
  max_range: 100.0 # can be also changed in the CLI
  min_range: 5.0

mapping:
  max_points_per_voxel: 20

adaptive_threshold:
  initial_threshold: 2.0
  min_motion_th: 0.1
